"""
Django settings for realshop project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
#Id : codekunst
#Pw : nono1919!
from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--n47rqjb%i!a!nd$s3l6ao_=1^nz4qc^dpq$uugfzu_8ut%km)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shops',
    'widget_tweaks',      
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'realshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'realshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'shops.validators.CustomPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'ko'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#Auth Settings

AUTH_USER_MODEL = 'shops.User' #이걸 써줘야함
MEDIA_ROOT = os.path.join(BASE_DIR,"media") #파일 경로를 django에게 알려줌
MEDIA_URL = "/uploads/"     #미디어파일(사용자가 올리는 파일) 경로

AUTHENTICATION_BACKENDS = [     # 복붙 해줘야해요 :)

    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',

]

ACCOUNT_SIGNUP_REDIRECT_URL = "main"
LOGIN_REDIRECT_URL = "main"
ACCOUNT_LOGOUT_ON_GET = True            #로그아웃시 바로 로그아웃
ACCOUNT_AUTHENTICATION_METHOD = "email" #email로 로그인
ACCOUNT_EMAIL_REQUIRED = True           #email은 필수 입력  
ACCOUNT_USERNAME_REQUIRED = False       #이름은 필수 입력아님
ACCOUNT_SESSION_REMEMBER = True         #로그인 유지
ACCOUNT_SIGNUP_FORM_CLASS = "shops.forms.SignupForm"  
                                        #signup 할때 shops안에 있는 signupform을 사용
SEESION_COOKIE_AGE = 3600               #세션 쿠키 유지 시간 3600초 default는 2주
ACCOUNT_PASSWORD_INPUT_RENDER_VALUE = True  #비밀번호가 사라지지 않고 남아있음
ACCOUNT_EMAIL_VARIFICATION = "none" 
#mandatory : 이메일 인증 완료까지 로그인 불가
#optional : 이메일 인증 안해도 로그인 가능 -> default 값
#none : 이메일 인증 필요없음
ACCOUNT_CONFIRM_EMAIL_ON_GET = True     #인증 이메일
ACCOUNT_EMAIL_CONFIRMATION_AUTHENRICATED_REDIRECT_URL = "account_email_confirmation_done"    #유저가 로그인 됐을때
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = "account_email_confirmation_done"        #유저가 로그인 안됐을떄
PASSWORD_RESET_TIMEOUT_DAYS = 3         #비밀번호 재설정 링크 유효기간 3일
ACCOUNT_EMAIL_SUBJECT_PREFIX = ""       #오버라이딩시 항상 앞에 도메인이 붙게 되서 그걸 제거하는 세팅
# Email Settings

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
